Problem Statement:
    Consider yourself to be sam who is data scientist. He has been invited as a guest lecturer at the college to take the session on numpy.

In [ ]:
Task to be performed:
    1. Intialize the numpy array of 5*5 dimension wtih all values to be 0

In [2]:
import numpy as np

In [4]:
a = np.zeros((5,5),dtype= int)

In [5]:
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [6]:
#or
b = np.full((5,5),0)

In [7]:
b

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Task 2.:
    Create a numpy array with intial value 10 and final 100 with interval of 5 between each value.

In [17]:
c = np.arange(10,105,5)

In [18]:
c

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [ ]:
Task 3.:
    Create 2D array with values (10,20,30,40,50,60) and set the dimension to be 2*3
    a. Print the number of elements in the array.
    b. Get the data type of the array.
    

In [19]:
d= np.array([10,20,30,40,50,60]).reshape(2,3)

In [20]:
d

array([[10, 20, 30],
       [40, 50, 60]])

In [21]:
d.dtype

dtype('int32')

Task 4:
    create first numpy array with values (1,2,3). Create second numpy array with value (4,5,6).
    perform the simple arithmetic operation on these two numpy arrays:
        a. Addtiton
        b. Substraction
        c. Multipliaction
        d. Division
        

In [22]:
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])

In [25]:
n1


array([1, 2, 3])

In [26]:
n2

array([4, 5, 6])

In [27]:
n1+n2

array([5, 7, 9])

In [28]:
#or
np.add(n1,n2)

array([5, 7, 9])

In [30]:
np.subtract(n1,n2)

array([-3, -3, -3])

In [31]:
#or
n1-n2

array([-3, -3, -3])

In [32]:
np.multiply(n1,n2)

array([ 4, 10, 18])

In [33]:
#or
n1*n2

array([ 4, 10, 18])

In [37]:
n1/n2

array([0.25, 0.4 , 0.5 ])

In [38]:
np.divide(n1,n2)

array([0.25, 0.4 , 0.5 ])

Task 5:
    Create a numpy array with values 10-90, and set the shape to be 3*3
    a. Extract only the 3rd column from the numpy array
    b. extract only 2nd row from the numpy array
    c. Extract those cell at the intersection of first two rows and first two coulumns

In [43]:
z= np.arange(10,91,10).reshape(3,3)

In [44]:
z

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [47]:
z[:,2:]

array([[30],
       [60],
       [90]])

In [46]:
z[1,:]

array([40, 50, 60])

In [50]:
z[0:2,0:2]

array([[10, 20],
       [40, 50]])

# Assignment Part II

Task 1:
create a function that takes dimension as a tuple e.g (3,3) and numeric value and returns a numpy array of given dimnesion filled with the given value e.g: solve((3,3),5) will return.

In [52]:
def func(a,b,c):
    d = np.full((a,b),c)
    return d

a = int(input())
b = int(input())
c = int(input())
print(func(a,b,c))

3
3
5
[[5 5 5]
 [5 5 5]
 [5 5 5]]


Task 2:
create a method that takes a numpy array of same dimensions sum them and return the answer. 

In [54]:
def math(a,b):
    sum1=(a+b)
    return sum1

a = np.array([10,20,30])
b = np.array([40,50,60])
print(math(a,b))



[50 70 90]


Task 3:
Given a 2D array of N*M dimension, Write a function that accepts this array as well as two numbers N and M. The method should return to the top-left N*M sub matrix

In [64]:
def math1(v):
    return v[:2,:2]

v = np.array([[1,2,3],[4,5,6],[7,8,9]])
math1(v)

array([[1, 2],
       [4, 5]])

Task 4:
Given 1 dimensional numpy array. Write a function that accepts this array as a parameters. The method should return a dictionary with 'mean' and 'std_dev' as a key and array's mean and array's standard deviation as values


[1,1,1]

solution (arr) -> should return :
{'mean': 1.0, 'std_dev' : 0.0}

In [65]:
def math3(z):
    a = np.mean(z)
    b= np.std(z)
    dict= {'mean':a, 'std_dev':b}
    return dict

z = np.array([1,1,1])
math3(z)

{'mean': 1.0, 'std_dev': 0.0}